

import '../styles/globals.scss'

import { Inter } from 'next/font/google'
import { Heebo } from 'next/font/google'
import Navbar from '@/components/navbar'
import Footer from '../components/footer'



const inter = Inter({ subsets: ['latin'] })
const Heebos = Heebo({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: "--font-exo2"

})

export const metadata = {
  title: 'קורסים אונליין',
  description: 'Generated by create next app',
  icon: 'favicon.png'
}

export default function RootLayout({ children }) {
  return (      
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="path-to-your-favicon" />
      </head>
      <body className={`${inter.className} ${Heebos.className}`}> 
      
      <main> {children} </main>
      {/* <Footer/> */}
      </body>
    </html>
  )
}
